name: Deployment Steps

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: 'echo deployed'
  # - id: 'auth'
  #   uses: 'google-github-actions/auth@v1'
  #   with:
  #     credentials_json: '${{ secrets.GCP_SA_KEY }}'

  # - name: Set up Google Cloud SDK
  #   uses: google-github-actions/setup-gcloud@v1
  #   with:
  #     project_id: ${{ secrets.GCP_PROJECT_ID }}

  # - name: Configure Google Cloud SDK
  #   run: |
  #     echo "${{ secrets.GCP_SA_KEY }}" > credentials.json
  #     gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
  #     gcloud config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}

  # - name: SSH to Compute Engine instance
  #   uses: appleboy/ssh-action@master
  #   with:
  #     host: ${{ secrets.GCP_INSTANCE_IP }}
  #     username: ${{ secrets.GCP_INSTANCE_USERNAME }}
  #     key: ${{ secrets.GCP_SSH_KEY }}

  #     # Commands to execute on the instance
  #     script: |
  #       cd Movie-Night-Discord-Bot/Discord\ Bot/
  #       git pull origin master --rebase --autostash
  #       npm install --production
  #       pm2 restart index.js 