name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - master
  workflow_run:
    workflows:
      - Manual Review
    types:
      - completed

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: 'Discord Bot/package.json'

      - name: Log changes
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Update in version: ${{steps.check.outputs.changed}}"'

  deploy_if_updated:
    needs: check-version
    if: needs.check-version.outputs.changed == 'true'
    uses: ./.github/workflows/deployment_steps.yml
    with:
      environment: Automated

  manual_deploy:
    needs: check-version
    if: needs.check-version.outputs.changed != 'true'
    uses: ./.github/workflows/deployment_steps.yml
    with:
      environment: Production

