on: workflow_dispatch
jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Create Text File
        run: |
          # Create a plain text file with key-value pairs for all secrets
          for secret_name in ${{ steps.get_secret_names.outputs.secret_names }}; do
            secret_value=${{ env[secret_name] }}
            echo "$secret_name=$secret_value" >> my-secrets.txt
          done

      - name: Debug my-secrets.txt
        run: |
          cat my-secrets.txt
          ls -lah

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets-file
          path: my-secrets.txt

  get_secret_names:
    runs-on: ubuntu-latest
    outputs:
      secret_names: ${{ steps.set_secret_names.outputs.secret_names }}
    steps:
      - name: Set Secret Names
        id: set_secret_names
        run: |
          env | awk -F= '{print $1}' > secret_names.txt
          echo "::set-output name=secret_names::$(cat secret_names.txt)"