on: workflow_dispatch
jobs:
   create-envfile:
     runs-on: ubuntu-latest

     steps:
      - name: Create Text File
        run: |
         for secret_name in ${{ env.SECRETS }}; do
          secret_value=${{ secrets[secret_name] }}
          echo "$secret_name=$secret_value" >> my-secrets.txt
         done
        env:
         SECRETS: ${{ join(secrets, '\n') }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
         name: secrets-file
         path: my-secrets.txt